version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - aws cloudformation package --template-file template.yml --output-template-file package.yml --s3-bucket afbuckets3

artifacts:
  type: zip
  files:
    - template.yml
    - package.yml