AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  S3DocumentsBucketName:
    Description: 'The name of the S3 bucket'
    Type: String
  ApiKeyRequired:
    Description: 'API Key required to call API'
    Type: String
    Default: 'true'
    AllowedValues:
    - 'true'
    - 'false'
  DomainName:
    Description: 'Domain name'
    Type: String
  CertificateArn:
    Description: 'Certificate arn'
    Type: String
  HostedZoneId:
    Description: 'Hosted zone ID'
    Type: String
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      Events:
        HelloWorldApi:
          Type: Api
          Properties:
            RestApiId: !Ref API
            Path: /hello
            Method: POST      
      Policies:
        - S3WritePolicy:
            BucketName: !Ref S3ZipBucket
        - S3ReadPolicy:
            BucketName: !Ref S3ZipBucket
        - S3ReadPolicy:
            BucketName: !Ref S3DocumentsBucketName
      Environment:
        Variables:
          S3_BUCKET_ZIP: !Ref S3ZipBucket
          S3_BUCKET_ORIG: !Ref S3DocumentsBucketName
  S3ZipBucket:
    Type: AWS::S3::Bucket
  API:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth: 
        ApiKeyRequired: !Ref ApiKeyRequired
        UsagePlan:
          CreateUsagePlan: PER_API
          Description: Usage plan for this API
          Quota:
            Limit: 500
            Period: MONTH
          Throttle:
            BurstLimit: 100
            RateLimit: 60
          UsagePlanName: DefaultUsagePlan
      #tutta questa parte però va parametrizzata
      Domain:
        DomainName: !Ref DomainName
        CertificateArn: !Ref CertificateArn
        Route53:
          HostedZoneId: !Ref HostedZoneId