AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      Events:
        HelloWorldApi:
          Type: Api
          Properties:
            Path: /
            Method: GET      
      Policies:
        - S3WritePolicy:
            BucketName: !Ref S3ZipBucket
        - S3ReadPolicy:
            BucketName: !Ref S3ZipBucket
      Environment:
        Variables:
          S3_BUCKET_ZIP: !Ref S3ZipBucket
  S3ZipBucket:
    Type: AWS::S3::Bucket           